### ISSUE TITLE
Planner

### ISSUE THREAD

**Issue by livibetter** [alexdantas/tcalc--#1]
## Why

Since I am the hope the one to bring up selfcoffee/firstmug#3, I think I should explain what I expect to see what this project to achieve. But first, the inspirational source, [@nassa/tcalc](https://github.com/nassa/tcalc):

![tcalc b849121271336cfb4d8cf91d05e8003573256aa5 2013-06-11](https://cloud.githubusercontent.com/assets/30909/3422944/0875cdec-ff74-11e3-8999-5b11825510c5.png)

tcalc has everything I need except:
1. No support for mouse
2. Too long in layout
3. No license is specified, see nassa/tcalc#1, therefore you can't safely work on it

I have tried many calculators, but one in terminal with button looks, tcalc is the only one. Almost all are relying on typing in.  This is why we (@livibetter and @alexdantas) started this project.
## Mockup

tcalc actually has too many features than I need, I don't need `()`, text input editing with cursor. What I am looking would looks like the following text mockup for a rough idea:

```
               123.456 |
-----------------------+
 C |  7 |  8 |  9 |  / |
---+ ---+ ---+ ---+ ---+
+/-|  4 |  5 |  6 |  * |
---+ ---+ ---+ ---+ ---+
 % |  1 |  2 |  3 |  - |
---+ ---+ ---+ ---+ ---+
OFF|  0 |  . |  = |  + |
---+ ---+ ---+ ---+ ---+
```

---

-- _The Buttons Planner Committee_

**Comment by alexdantas** [comment]
A simple doubt struck me now - would you like if the layout expanded to the size of the current terminal?
My guess would be no - it should have a fixed size.

But an alternative would be to make it always expand to the size of a virtual ncurses `WINDOW*` and, by default, that window would have a fixed size.
If one would give a flag, say `--expand`, then that virual `WINDOW*` would be equal to ncurses' `stdscr`.

Like the following pseudocode:

```
virtual_window = new window(fixed_size)

if (argument("--expand"))
    virtual_window = terminal_window

layout.expand_to(virtual_window)
```

**Comment by livibetter** [comment]
Frankly, I have no idea, I just want some buttons to click on. Resizing to fill up is nice, because every font size are different in each terminal, that would look at least similar in calculator size.
